# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.destroy_all
u = User.new
u.email = "gearlanceapp@gmail.com"
u.first_name = "Gear"
u.last_name = "Lance"
u.city = "Chicago"
u.state = "IL"
u.password = "gearlance"
u.password_confirmation = "gearlance"
u.user_bio = "Bacon ipsum dolor sit amet tenderloin swine meatball, jerky bacon pork ribeye spare ribs leberkas salami turducken chicken ham. Strip steak venison pancetta shoulder. Tail swine pork chop, cow ham brisket venison bacon jerky pastrami doner jowl ground round. Short loin sirloin pancetta bresaola ham strip steak"
u.admin = true
u.save

Category.destroy_all
categories = [
  { name: "Camera", slug: "cameras" },
  { name: "Lens", slug: "lenses" },
  { name: "Lights", slug: "lights" },
  { name: "Other", slug: "other" }
]

categories.each do |category|
  c = Category.new
  c.name = category[:name]
  c.slug = category[:slug]
  c.save
end

Item.destroy_all
items = [
  { category_id: Category.find_by_name("Camera").id, name: "Vintage KODAK VIGILANT JUNIOR SIX", photo_url: "https://lh4.googleusercontent.com/public/6Alpgit5FGtWS_eQZw4GXIjHcqgu9_QzOO3eDwAnR_C-sjQCvDtn3_dkWDxz3aRM-ZnATAqGzkoOq5_-TV8ZZx5BZfOzGM-O_atQE9u3lCLHBoRmMaz2Dut7_wnuRdVr2VUehgjE-FHJ80AxNjx1hUzfYNsPWJPxU0bSH8uKBXX4wnjQ48477ahyAOtFJWL_vlkaY-BBTharSQr1aoRS7xg5PF-jXpOwo0aBRsUUQdY3kgh4_cbsSQ0C0_lN=s120-c", description: "Vintage KODAK VIGILANT JUNIOR SIX - 20 Antique Camera w Bellows from a local estate. Camera appears to be in good condition", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "Polaroid The 800 Land Camera Vintage Instant Film Camera", photo_url: "https://lh4.googleusercontent.com/public/tr4h-lOJWrwF7LoEkX-ejKgPYH6seObN66eir7TC7MNuMxQ1VasNeHrpJlQbrPqgNO1RVgvoqQOqdeu2oVG71z3EdhEB9auuq3TCYqsTDevysw0mWcmLvYIgu3r2ZZrtMDvAJYbd8FNlf18hO2p_nNRmFzXZzUQgReS6RHHszkXEZYwPsS2CgJ0=s120-c", description: "Brand: Polaroid Model: The 800 Film: Type 40 Rollfilm Condition: Excellent condition with no damage and only faint signs of use.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "Vintage Camera Argus C2 50mm Brick 1938", photo_url: "https://lh6.googleusercontent.com/public/816Ctn9sKy1GzTsdFn1QUKIsSqjEegEwrVxgMjeuLqDVXoZSzFUkrbOMpWjZLvJc0vxjOFMW8MZqXd-m8b1Swmv82uzVXMrUChrffkWVVf6b-tM5RqYk_DsUiGLlMqhQboeZXg0fh8_NX1Phgbq2HjIOGMgwDvpKKb-4_TjkdzC7Vg=s120-c", description: "This camera is a gem! Dubbed 'the brick', the Argus C-2 was a popular solid durable camera with coupled rangefinder made in 1938 by Argus", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "1930s Kodak Six-20 Popular Brownie Box Camera 1937 Antique Camera", photo_url: "https://lh6.googleusercontent.com/public/icCk-5CgZmveMaKafolCHOOrQyd0_LtrOkOgQOa_v1QOR7bsYlVWsKUnUP8B9LqXOe6MJJnxrycLAG-_uFKt65KFHl0IeZAo9TAVCJXwWuk66W4CvUz3mRsYX5pM0NGihO3jP_ozMFxSQaSR_qFMCZc6Go84QiYtWlmYSCbtcjzATw=s120-c", description: "A real late-1930's gem! This is a UK-made Kodak Popular Brownie 620 camera. It takes 620 roll film", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "Canon XA10 HD Professional Camcorder", photo_url: "http://www.42photo.com/images/products/prod_m/105614_m_749467.jpg", description: "Go Pro or Go HOME", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "HERO3: Black Edition", photo_url: "http://cbcdn2.gp-static.com/uploads/flipbook_photo/image/1/01.jpg", description: "The Wi-Fi enabled HERO3: Black Edition is the most advanced GoPro, ever. No expense was spared during its development, resulting in a GoPro that is 30% smaller, 25% lighter and 2x more powerful than previous models. Wearable and gear mountable, waterproof to 197' (60m), capable of capturing ultra-wide 1440p 48fps, 1080p 60 fps and 720p 120 fps video and 12MP photos at a rate of 30 photos per second, the HERO3: Black Edition is the world's most versatile camera. Built-in Wi-Fi, GoPro App compatibility and the included Wi-Fi Remote (normally a separate $79.99 accessory) make the HERO3: Black Edition all the more versatile, still.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "Canon VIXIA HF R400 High-definition camcorder with 32X optical zoom", photo_url: "http://a248.e.akamai.net/pix.crutchfield.com/ImageHandler/fixedscale/900/900/products/2013/2/280/x280HFR400-F.jpeg", description: "What's the difference between getting the shot no one thought you'd get — and another forgotten clip sitting in the digital flotsam on some forgotten hard drive or memory card? It might just be the Canon VIXIA HF R400 camcorder. With a 32X optical zoom (plus a useful 53X advanced mode), the 'R400 certainly has a long reach. But what makes the winning difference is the sophisticated stabilization, which smooths out shakes even on long telephoto shots. So go ahead: get that shot of your daughter at the top of the cheerleader pyramid on the opposite sideline. Be fearless when you're capturing your wife receiving a plaque at the huge company awards ceremony. You've got a camcorder that can handle the tough stuff.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "JVC - GCPX100BUS - 3.0in, Wifi, F1.2 , LED", photo_url: "https://lh4.googleusercontent.com/public/3Odbu-D6PfaS_nNnWloSHkjOeKFOkEcMmRq3mt2IGA1FDjahwjJx4ZUX44h_biq1P7sIq0qLyEL5MiCseTyKdkFuyBZek4bsb_AvKJpA4MLG6alBb1lrftxhassTw6uVBezINxTWhVKbvlX16Kri9BtVxVIAww=s150-c", description: "JVC - Everio - Handheld - High Definition - 1080p - 720p - 1080i - Wireless - HDMI - SD Card - 12.8 megapixel sensor - AVCHD - MPEG-4 - 10x optical zoom - Image Stabilizing", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "JVC ADIXXION GC-XA1 5.0 MP Camcorder - 1080p", photo_url: "https://lh5.googleusercontent.com/public/4xSWkKm-dGzIsoajC65tIvMPtt40YLKsjhA6TGQPni0sWeO27y520FljfqGfUK743b8vAtQF8PuzS2xTHqG_uJ-iUY9wpJmFP6RiZQkShAJevcKPQdFLXIHmxJmbaaFRFAKbaVL2bzjl-tXBHWMMVFE=s150-c", description: "JVC - ADIXXION - Helmet - High Definition - 1080p - 720p - Waterproof - Wireless - USB - HDMI - SD Card - 5 megapixel sensor - MPEG-4 - Image Stabilizing - Fixed Focus", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "JVC Everio GZ-E200 1.5 MP Camcorder - 1080i - Black", photo_url: "https://lh5.googleusercontent.com/public/myR1qFWQJqa3VJCl3zfhMNxlqA0g5oZF3d_KRYpQBmGAUBygkO7HCeabAI4ZQdxKCALnFpWnKsYw7NuArquqAl-lXDxNIkqD-7XtAekjllJ_NnC3FddPhSk1NTm8ML-UjCw68a5Z4OMoOtDQLrh4cb0=s150-c", description: "JVC - Everio - Handheld - High Definition - 1080i - USB - HDMI - Composite - SD Card - 1.5 megapixel sensor - Night Mode - AVCHD - 40x optical zoom - Image Stabilizing - Manual Focus - Automatic Focus", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "JVC - GZEX355BUS - 1920x1080, 16GB, Wifi, 3.0in, Black", photo_url: "https://lh5.googleusercontent.com/public/G28Uw70MGp2hXEz4AVbnALQaenHNSyQXwHYIHQO41qugrUOb9qkZsTvj1qTrnf256iMnvXX5DC20HiDkCUWhymvnuW-MQkQcx95TTDParsga2r6ekaIc-feMOMZIgnfaQkh3USZvl4zdaunYnrxIAX7DrgqxDa2qeFl1Xh0epvPgD-sHhdgLYeorDdMIQOFJ=s150-c", description: "JVC - Everio - Handheld - High Definition - 1080p - Wireless - HDMI - SD Card - 2.5 megapixel sensor - 40x optical zoom - Image Stabilizing", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "JVC ADIXXION GC-XA1 5.0 MP Camcorder - 1080p", photo_url: "https://lh5.googleusercontent.com/public/4xSWkKm-dGzIsoajC65tIvMPtt40YLKsjhA6TGQPni0sWeO27y520FljfqGfUK743b8vAtQF8PuzS2xTHqG_uJ-iUY9wpJmFP6RiZQkShAJevcKPQdFLXIHmxJmbaaFRFAKbaVL2bzjl-tXBHWMMVFE=s150-c", description: "JVC - ADIXXION - Helmet - High Definition - 1080p - 720p - Waterproof - Wireless - USB - HDMI - SD Card - 5 megapixel sensor - MPEG-4 - Image Stabilizing - Fixed Focus", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "JVC GY-HM710U Camcorder - 1080p", photo_url: "https://lh5.googleusercontent.com/public/L4_WHelWpuQcU8GZwcgnbdZbwKJak4o13Dops9DzQDk3AjJTddXvIMwjlbxN_AEmSnsfYmEay4szM7q1GfIGkVC5RjtrklubOHEzOfrSQ11Xk2MMwB0RHZVyrxA=s120-c", description: "JVC - Handheld - High Definition - 1080p - USB - FireWire - Component - Composite - HD-SDI - SD Card - Night Mode - MPEG-2 - AVI - 14x optical zoom - Interchangeable Lens - Manual Focus", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "JVC - GCPX100BUS - 3.0in, Wifi, F1.2 , LED", photo_url: "https://lh4.googleusercontent.com/public/3Odbu-D6PfaS_nNnWloSHkjOeKFOkEcMmRq3mt2IGA1FDjahwjJx4ZUX44h_biq1P7sIq0qLyEL5MiCseTyKdkFuyBZek4bsb_AvKJpA4MLG6alBb1lrftxhassTw6uVBezINxTWhVKbvlX16Kri9BtVxVIAww=s150-c", description: "JVC - Everio - Handheld - High Definition - 1080p - 720p - 1080i - Wireless - HDMI - SD Card - 12.8 megapixel sensor - AVCHD - MPEG-4 - 10x optical zoom - Image Stabilizing", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "Panasonic HC-X920 12.76 MP Camcorder - 1080p - Black", photo_url: "https://lh5.googleusercontent.com/public/66Pbrk6v9opEQ_cCyRcV6B-sw5jRmYRp1yYXEtqNJgShAgXQNpMyrYp9S6JowWXcIzZnC_DFDJ_-jIZXupsRnOCu4jERtSeQZzr8rsSATpW74H9e7sjKwGYl-SwTtRWtn1UcoX3g_IsMIqeDK64EnSY=s150-c", description: "Panasonic - Handheld - High Definition - 1080p - USB - HDMI - Composite - SD Card - 12.76 megapixel sensor - Night Mode - 3D - AVCHD - 12x optical zoom - Image Stabilizing - Manual Focus - Automatic Focus", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "Panasonic HX-WA2 14.4 MP Camcorder - 1080p - Blue", photo_url: "https://lh6.googleusercontent.com/public/aBsuaeEpiPG-mBpQmiSnme-A3REg1gK5etUT3RQzMccEoRXtmwQ15x1qLOnTVybacsaWGZvZi35vJSCg3RA2awf6ElVUwe-QlIMCEFxMiS2MUUgskTzOk_YS-7yi1wpcXg3gSvpllg=s120-c", description: "Panasonic - Pocket - High Definition - 1080p - 720p - Waterproof - USB - HDMI - Composite - SD Card - 14.4 megapixel sensor - Night Mode - MPEG-4 - 5x optical zoom - Image Stabilizing - Manual Focus - Automatic Focus", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "Sony Super HAD CCD with Intelligent Infrared and 3.8mm Wide Lens", photo_url: "http://ep.yimg.com/ca/I/yhst-36953680823486_2261_21367563", description: "The MONALISA SERIES Dome is both Weather Proof and Vandle Proof. It also has Infrared, so it is a true Day/Night Camera. The 600 Lines of Ultra High Resolution offers a superb digital surveillance image that can be easily identified. This camera is furnished with a Weather Proof / Vandle Proof Wall Mount Bracket so you can conveniently mount onto any side wall. ", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "Speedo Waterproof Digital Camera", photo_url: "http://www.swimoutlet.com/photos/options/22108-26549-T.jpg", description: "Whether you're swimming with dolphins or just messing around with friends, this Waterproof Digital Camera from Speedo is the perfect way to capture all your underwater memories. Make sure you're always at the ready to snap a picture or record a video. Camera includes a Li-Ion battery, AV and USB Cable, Hand strap, AC adaptor, software CD and a carrying bag. ", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "Nikon Coolpix S31 Shock & Waterproof Digital Camera (Blue)", photo_url: "http://img.rakuten.com/PIC/48825884/0/1/300/48825884.jpg", description: "Nikon Coolpix S31 Shock & Waterproof Digital Camera Photo fun for the family. Finally a family-friendly camera you can take everywhere! The Nikon Coolpix S31 is waterproof shockproof and dustproof so even the roughest conditions wont stop you from recording precious memories. Shoot beautiful 10-megapixel photos and 720p HD videos in the rain at the beach in the pool or sandbox -- places you wouldnt dare bring your old camera -- with a 3x zoom Nikkor glass lens. Plus with oversized buttons super simple operation and a bright 2.7-inch LCD every member of the family can have a turn. Key Features: Share the magic -- In-camera slideshows with music Instantly review and laugh over the pictures and movies of the day with the easy slideshow mode. Select playback effects and built-in music to accompany your show -- fun to share with friends and family. Connects easily to a TV (optional EG-CP14 audio video cable required). Share the sights and sounds of your adventure. Master the camera in no time -- Simple convenient operation for stress-free shooting The Coolpix S31 is so easy to use anyone can take great photos and videos with it. Just turn the camera on point shoot and marvel at the results. For maximum point-and-shoot convenience select Easy Auto Mode. It automatically optimizes the camera settings for each shot no matter how challenging the situation. Youll be free to enjoy the moment while you capture it. Frame the perfect shot With 3x optical zoom power the Coolpix S31s genuine NIKKOR glass lens is great for everything from wide-angle group shots to close-up candid portraits. No Zoom 3x Optical Zoom Dont sweat a little camera shake Electronic Vibration Reduction helps keep the shot steady even if your hands are not. Say goodbye to blurry photos shaky videos and tripods. No Image Stabilization With VR Image Stabilization Capture the sights and sounds -- 720p HD videos w/sound bring your memories to life When a photo alone wont do press the dedicated movie button and instantly start recording 720p HD video in widescreen format while the built-in microphone captures the sounds of the moment in high fidelity. When youre ready to share your creations use an optional audio video cable (EG-CP14) to connect to your compatible TV. Your friends and family will see your movies come to life on the big screen. Turn the ordinary into extraordinary Easily apply fun and creative Image Effects like Highlight colors add a diorama effect soften pictures and more right from the camera -- no need for additional photo or video-editing software.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "Intova 14MP Digital Sports Camera with 180 Waterproof Housing", photo_url: "http://www.swim2000.com/images/product_gen/300x300/IC14.jpg", description: "The IC14 is Intovas newest digital camera that features a 1/2.33 14 megapixel CCD image sensor for high resolution photography, 1/2000th second fast shutter speed and an enhanced Digital Signal Processor. This model is ideal for capturing fast moving subjects underwater. With up to 720p HD video resolution, the IC14 provides for exciting and fun opportunities in capturing action and adventures. Other camera features include 5X Optical Zoom / 6x Digital nZoom, 2.7 LCD and Lithium ion battery that does not require removal for recharging via USB cable. The IC14 uses SDHC memory cards up to 32 GB (not included). The newly designed sleek external housing is waterproof to 180 feet/54 meters and features dual O-rings to provide extra leak protection and 52 mm lens barrel thread that allows for addition of filters and other accessories.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "Old School F Nikon", photo_url: "http://media.treehugger.com/assets/images/2011/10/nilon20f-thumb.jpg", description: "Super cool description of item goes here.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "Nikon - D3100 14.2-Megapixel DSLR Camera with 18-55mm VR Lens - Red", photo_url: "http://pisces.bbystatic.com/image2/BestBuy_US/images/products/3099/3099128_sa.jpg;canvasHeight=166;canvasWidth=210", description: "Super cool description of item goes here.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "Canon Powershot SX50 HS 12.1 Megapixel Digital Camera", photo_url: "http://www.42photo.com/images/products/prod_m/107138_m_IMG_272168.jpg", description: "Super cool description of item goes here.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "Polaroid Z2300 10-megapixel digital instant camera (White)", photo_url: "http://a248.e.akamai.net/pix.crutchfield.com/ImageHandler/fixedscale/400/300/products/2013/9/146/x146Z2300W-F.jpg", description: "Super cool description of item goes here.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "Canon A1400 16MP 5X Optical Zoom Black Digital Camera", photo_url: "http://www.officemax.com/catalog/images/397x353/23937821i_01.jpg", description: "Super cool description of item goes here.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "Nikon COOLPIX L820 16MP Digital Camera with 30x Optical Zoom", photo_url: "http://img1.targetimg1.com/wcsstore/TargetSAS//img/p/14/44/14449457_130307103000.jpg", description: "Super cool description of item goes here.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "Nikon Black D3200 Digital SLR Camera", photo_url: "http://i.walmartimages.com/i/p/00/01/82/08/25/0001820825492_60X60.gif", description: "Super cool description of item goes here.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "RCA Camcorder", photo_url: "http://th03.deviantart.net/fs71/PRE/f/2012/365/8/e/1986_rca_pro_wonder_vhs_camcorder_by_tikikah_the_phoenix-d5pvh9r.jpg", description: "Super cool description of item goes here.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Camera").id, name: "Fake Lens", photo_url: "http://2.bp.blogspot.com/-MwIlpDCqbX0/TmIjim9nYjI/AAAAAAAAACo/PDIpIiFqzEM/s1600/camera-lens-icon.jpg", description: "Super cool description of item goes here.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Lights").id, name: "Musician's Gear Stage Lighting System 838", photo_url: "https://lh3.googleusercontent.com/public/EAWkKgKJ71gQeo7AcJcP805ffPYiQVW7bMX8SqQEW2xaH65HMp8eLtINAuOQCY8s_qmvkjn4ZUM0xL_QbNV_C7dOUJ_adHomXk7BXDnApRum6k7hrBgcEdQ25Zaw5N0tz2xzCVQmPpDy7oaaBBfda-LDpIu5BCHuquhCwtSYtQR_d6aauO-ctaOAWJb8xDbXwK1wb8HK6KO7KsORKg=s220-c", description: "Includes 8 PAR 38B Cans, 2 Odyssey LT-P2 tripod lighting stands, Chauvet SF-9005 Timer Controller, and 2 Chauvet SR-8 Relay Packs. Par 38B Cans Each PAR Can features a medium screw-base socket with a power cord and gel frame than can be used with any medium screw-base 110V lamp (sold separately.) Odyssey LT-P2 tripod lighting stands Black aluminum stands with T bars extend to 12'. Chauvet SF-9005 Timer Controller This full-featured controller includes 8 on/off/chase switches, 2 chase options: 16 patterns sound-activation or timed chase 20sec - 15min, 16 patterns of sound activation, plus fog and strobe controllers. 25' cable. SR-8 Relay Packs Feature 8 switched power sockets that correspond to channel 1-8 on the multifunction switch panel and one unswitched power socket for constant on item. What is a Relay Pack? Relays allow you to control non-DMX lighting via a DMX controller. The relay pack contains multiple plugs, each of which correspond to a channel of DMX. When units are plugged into this relay pack, they become dependent upon the relay for power. These lights are either on or off. The function of the relay is to control that signal. As the slider of a DMX controller is raised, a certain value will represent on for the relay pack, which will cause the light to turn on. How To Use 2 Relay Packs with the SF-9005 Timer Controller: Two SR-8 relay packs may be run off one multifunction switch panel. Simply connect an SF-EXCB 9-pin extension cable (see item # 801696) from the line out on one SR-8 relay pack to the line in on another relay pack. ** Please note maximum load per relay pack is 15amps or 1800watts.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Lights").id, name: "American DJ Flat Par TRI18X Stage Light FLA837", photo_url: "https://lh3.googleusercontent.com/public/p19N4bqJ2IZ4tM1KVYng0wOTOdpbEar54xGL8LzBTN-oM3Z8UPkgD31_FoTCHuZU-GA377tIaN_-K_7Jy7o1mHE9eEXu_Ozte3J4_9p4HDdzimvfX35u34Da2iMGBwuRFL9Y8gMXJwDuHA3pt4gxD0ITZscwVQXgftM29C82MA=s220-c", description: "The ADJ Flat Par TRI18X is a professional 'low profile' LED Par Can with extremely bright output. It features eighteen 3-Watt TRI LEDs (3-in-1 RGB) and will not cast any RGB shadows. The Flat Par TRI18X has seven different DMX channel modes, and may also run in Sound Active or Master/Slave modes. Users can also go 'wireless' with the ADJ LED RC wireless remote (sold separately). This LED Par Can also features: 32 Color Macros, Electronic Dimming (0-100%), IEC AC IN and OUT on side to daisy chain power and a 40-degree beam angle. The Flat Par TRI7's LEDs are rated at 50,000 hours, and only draws 56-Watts of power per fixture.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Lights").id, name: "MBT Dim4 Stage Lighting System", photo_url: "https://lh4.googleusercontent.com/public/IRv2WglsHjBpgHtkW8tD-NDFnXN3Zbef_NfmkdkAyVo_C37IlRK93IpozZJ2MPr2I6u1Jdlh314DZlZtSf3B4gMYmAiPFB55I0t484w8BnlqjeUvsgWHpxYWWnIT6mw72ujhSF3Og-8KDDK-JpEGhrOtNyY-jaSG5-R4JIQ=s220-c", description: "It is just a rack of lights... Oh, P.S. Standard extension cords not included.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Lights").id, name: "Chauvet 4Play CL Stage Lighting Effect", photo_url: "http://www.americanmusical.com/ItemImages/Large/CVT%204PLAYCLR.jpg", description: "The Chauvet 4Play CL Stage Lighting Effect is a pack-and-go LED moonflower lighting package that comes complete with its own carrying case. Four individually controllable heads in clear casings can be aimed to fill any room with red, green, blue and white beams. The Chauvet 4Play CL’s mounting bar features a pass-through to allow the unit to be quickly and easily added to an optional tripod or speaker stand. ", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Lights").id, name: "Chauvet 6 Spot 6 3W Color Changer DJ Lighting System", photo_url: "https://lh3.googleusercontent.com/public/wiKM4TqTF0n2fq6okAGyBpamnuFaiU0cHRYLF7EXI3vSWF-uHdm_G4xqWMuFn2BoAK5EdMyX_Q4A41er-FKyrBFG_o8eCRkRwGjxexx72VXxZgMTwAH20Adgl2o7TlmamsNrH_Nh1aLtL1poXxC1UIWuyKnPRe79Fqd0T-PyPoOjpYR9z3Qk1_pdN5P3E_K7HLvy8N3o19tDyIKtlzsdu6lwLtXoeNYP=s220-c", description: "Chauvet Model 6SPOT Now available at Hollywood DJ. Chauvet Tri-Color LED System Model 6SPOT Chauvet Model 6SPOT at Hollywood DJ The Model 6SPOT by Chauvet Its an LED powered, color-changer system complete with its own travel bag. Six individually controllable and positionable heads each contain a high-power tri-color LED that creates 7 popular colors. The unit can be controlled via DMX or by running automatic or sound-activated programs. The fixture easily slides onto most standard tripod stands or can be mounted onto truss.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Lens").id, name: "EOS Rebel T2i", photo_url: "http://www.dansdata.com/images/d60/lenses500.jpg", description: "Super cool description of item goes here.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Lens").id, name: "Lomokino Super 35mm", photo_url: "http://www.ubergizmo.com/wp-content/uploads/2011/11/17-LomoKino-Super-35.jpg", description: "Super cool description of item goes here.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Lens").id, name: "Canon EF 75-300mm f/4-5.6 III Telephoto Zoom Lens", photo_url: "http://s7d5.scene7.com/is/image/Staples/s0133421_sc7?$splssku$", description: "Super cool description of item goes here.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Lens").id, name: "Canon EF 70-300mm USM IS Lens", photo_url: "http://www.crutchfield.com.edgesuite.net/pix.crutchfield.com/ImageHandler/fixedscale/900/900/products/2005/280/x28070300iU-f.jpeg", description: "Super cool description of item goes here.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Lens").id, name: "Canon EF 100-400mm f/4.5-5.6L IS USM", photo_url: "http://overstockdigital.com/ovcat/product_thumb.php?img=images/canon100-400.jpg&w=250&h=161", description: "Super cool description of item goes here.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Lens").id, name: "Canon zoom lens", photo_url: "http://webobjects2.cdw.com/is/image/CDW/355656?$product_230$", description: "Super cool description of item goes here.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Lens").id, name: "TAMRON AFB008C700 (B008) 18-270mm/F3.5-6.3 Di II VC PZD Lens", photo_url: "http://images17.newegg.com/is/image/newegg/30-995-995-TS?$S300W$", description: "Super cool description of item goes here.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Lens").id, name: "Olloclip iPhone Camera Lens", photo_url: "http://a.tgcdn.net/images/products/frontsquare/eba9_olloclip_iphone_camera_lens.jpg", description: "Super cool description of item goes here.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Lens").id, name: "NIKON AF 70-300MM F4-5.6 G", photo_url: "http://used.natcam.com/newused/images/8005/NIKON_AF_70-300MM_F4-5PT6_G.jpg", description: "Super cool description of item goes here.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Lens").id, name: "Canon EF 70-200mm f/4L USM Lens", photo_url: "http://www.crutchfield.com.edgesuite.net/pix.crutchfield.com/ImageHandler/fixedscale/900/900/products/2009/03/280/x28070200L-f.jpeg", description: "Super cool description of item goes here.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Other").id, name: "Adventura 170 Shoulder Camera Bag - Black", photo_url: "http://snpi.dell.com/snp/images/products/mlrg/A4967169.jpg", description: "The Adventura™ 170 Shoulder Camera Bag from Lowepro® is a protective, lightweight, streamlined bag that’s packed with practical features. The thoughtfully organized shoulder bag has the zippered main compartment which features a quick-release buckle and rainflap lid, offering quick access to contents when bag is unzipped and extra protection when bag is fully closed. This bag comes with removable/adjustable shoulder strap, features a non-slip patch and sturdy snaphooks make connections secure. Plus, inside the fully padded interior, a soft tricot lining provides protection to your camera device and a burnt orange color making it easy to see gear while you work out of the bag. Additionally, the Adventura 170 has a zippered front pocket with memory card storage, padded grab handle and two pleated side pockets. Furthermore its two belt loops provide an added carrying option on the 170 model. With all these and more features, the Adventura 170 Shoulder Bag is the ideal choice for the DSLR or camcorder user, who’s looking for more than just a bag.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Other").id, name: "Piel Leather 2295 Deluxe Carry All Camera Bag", photo_url: "http://a248.e.akamai.net/origin-cdn.volusion.com/syj5v.zpnx6/v/vspfiles/photos/PI-2295-2T.jpg?1358767622", description: "Flap over, main zip pocket, inside film pocket, and front pocket. Shoulder strap and handle.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Other").id, name: "Case Logic DCB-309 SLR Camera Backpack (Black)", photo_url: "http://static.bhphoto.com/images/images200x200/871459.jpg", description: "The DCB-309 SLR Camera Backpack from Case Logic may appear compact on the outside but it sure holds its weight in gear. Stash your two DSLR bodies inside-one with a 70-200mm f/2.8 attached. And, there's room left over for two smaller lenses and a flash. Every photographer needs a laptop and this backpack will hold your 15 inch MacBook Pro or a 14 inch PC in a separate, padded zippered compartment. Not enough? Take along your tripod stored neatly within the side zippered pocket. Secure it with the included buckle and you're ready to head out for a day's shoot. Inside the bag, a padded divider system allows you to arrange the interior to accommodate whatever gear you need.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Other").id, name: "Lowepro Passport Sling II Camera Bag, Black/Red", photo_url: "http://www.adorama.com/images/300x300/LPPPS2BR.jpg", description: "Space for your camera gear and space for your personal gear, that's what you get with the discreet, modern and versatile Lowepro Passport Sling II Camera Bag (Black/Red). A customizable and removable camera box provides protection for a DSLR or CSC kit. Remove the box to use the sling without camera gear - it makes a great travel or day bag.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Other").id, name: "Crumpler 5 Million Dollar Home Camera Bag", photo_url: "http://l3.zassets.com/images/z/2/2/1/7/5/9/2217590-p-MULTIVIEW.jpg", description: "Whether you're a polished professional or an aspiring amateur, haul all your camera essentials in the 5 Million Dollar Home Camera Bag from Crumpler®. Bag is made from a water-resistant 900D outer, flamed polypropylene webbing and a triple strength S-Bend webbing attachment. Also, the bag includes an injection molded hook-and-loop and bonded nylon thread with bar tack stitching on all stress points.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Other").id, name: "Pelican™ 1510 Case with Padded Divider", photo_url: "http://rsk.imageg.net/graphics/product_images/pRS1-7296926w345.jpg", description: "Protect your camera and other gear with this watertight, crushproof and dustproof case from Pelican. It has a retractable extension handle and strong polyurethane wheels with stainless steel bearings that makes it great for travel. And, it features an open cell core, stainless steel hardware and unconditional lifetime guarantee.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Other").id, name: "Pelican™ 1440 Case with Padded Divider and Lid Organizer", photo_url: "http://rsk.imageg.net/graphics/product_images/pRS1-7466827w345.jpg", description: "Protect your camera and other gear with this watertight, crushproof and dustproof case from Pelican. It features an open cell core, stainless steel hardware and unconditional lifetime guarantee.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Other").id, name: "Pelican™ 1550 Case with Padded Divider", photo_url: "http://rsk.imageg.net/graphics/product_images/pRS1-7280272w345.jpg", description: "Protect your camera and other gear with this watertight, crushproof and dustproof case from Pelican. It features an open cell core, stainless steel hardware and unconditional lifetime guarantee.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Other").id, name: "Lowepro Scope Travel 200 AW", photo_url: "http://www.suitcase.com/media/catalog/product/cache/1/image/370x/9df78eab33525d08d6e5fb8d27136e95/s/c/scopetravel_200_front.jpg", description: "Roomy, rugged backpack design offers a spacious and durable carrying solution for birders and wildlife watchers who travel and spend long hours in the field", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Other").id, name: "Vanguard VGP-3200 Camera Hard Case", photo_url: "http://www.optics4birding.com/media/images/products/23225-1.jpg", description: "Vanguard VGP-3200 Camera Hard Case has a solid aluminum alloy frame with sleek, professional style and an interior of adjustable dividers and customizable foam for a great fit for a variety of fragile equipment. Great for airport travel, they’re rugged and ready to withstand rough travel and the dual locks with two keys keep your valuables safe. With a comfortable handle and removable reinforced carrying strap, Vanguard VGP 3200 camera hard case makes travel worry-free.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Other").id, name: "Sealife Deluxe Travel Protective Camera Case", photo_url: "http://mcdn.scuba.com/images/bags/Sealife-Deluxe-Travel-Protective-Camera-Case.jpg", description: "This is a great case to protect your camera, strobe(s) video light and large enough to carry some accessories. It can be carried on and could even be checked since you can add a lock. Great case for protecting your camera ", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Other").id, name: "Family Photo", photo_url: "http://4.bp.blogspot.com/_P_QbkiPZ9u4/SgnA3shu6sI/AAAAAAAAAyE/90Yd9muy7tE/s400/tree-humpers.jpg", description: "When was this ever a good idea?", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Other").id, name: "Smith-Victor Photoflood KT1500 - Continuous light kit - 3 head(s) x 1 lamp(s) - tungsten - 1500 W - AC", photo_url: "https://lh3.googleusercontent.com/public/u727YIqFewYcAi81-6g3IiadgKEHnGaqUUyydx7HgUO3l5eRUETY_cUB8BDsNTC9rHOkFoJDNQCA7AWJPmja2h5RcpxqNZUxcv-wdXtQHYyjbDYO2WXQvX6PK4wGRiBcwoqwmAh7cW44mwo5RmpxVy8bODA=s220-c", description: "Designed to fulfill basic lighting requirements at an exceptionally affordable price, the improved Smith-Victor KT1500U Thrifty Kit is an even better value. This kit features two 32 inch shoot-thru white umbrellas, two UM-6 umbrella mounts, 5/8 inch light stand adapters and Smith-Victor's Raven RS8 8' light stands. Enhanced 'through-the-reflector' umbrella mounting system places the umbrella close to the optical axis of the light for optimum control. The reflectors are chemically etched for maximum light dispersion", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Other").id, name: "Photographic Studio Light Tent Kit 30 inch Four Lights", photo_url: "http://www.skaeser.com/media/05/a20792912b7ec4c498e0f3_m.jpg", description: "This is a new photographic studio light tent kit with four  photographic fluorescent lights for  product photography by PBL.  Measuring 30in x 30in x30in  when opened and ready for use, this photographic light tent is made of a translucent nylon which is the perfect medium for creating a soft lighting environment for small products or collectibles of any kind.  With this photo product lighting kit you can get your light up and over the light tent as well as from the sides into the light tent.  Just direct the light through the side or top panels of the photo light tent to get the kind of lighting environment best suited to your subject.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Other").id, name: "Westcott uLite 2 Light Lighting Kit (120volt)", photo_url: "https://lh6.googleusercontent.com/public/LiNOSCMYiqPIjOMP6OI11vaAps0ieyeAr1JYJGdgR9h94MteyqJexw-TH-iqwx6P9K48ZTSxpA9B0PJkNfeBxd3K6Wdpj-nnFmwYtfics4cvwxFdheSmIvEaKEN3g2lKLmPFowyCFM5_qkx23DcKkVs=s220-c", description: "This lighting kit includes 2 uLite constant lights, 2 20 inch collapsible softboxes, 2 6.5' light stands, 2 500W photofloods and 1 coupon for free rental of 5'x6' scenic background. The softboxes attach easily to each flood light and collapse again for easy storage.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Other").id, name: "32 inch Umbrellas 9' Backdrops Daylight Photo Studio Lighting Kit", photo_url: "http://www.thelashop.com/images/P/01KIT008-108S3-302-G.jpg", description: "Perfect for any objects, such as portraits, costumes, furnishings, etc.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Other").id, name: "32 inch Umbrella Photo Lighting Continuous 3 Lights Kit with Case", photo_url: "http://www.thelashop.com/images/P/01UMS002-VL-303UL-B-p01.jpg", description: "The brand new professional photo umbrellas kit(303UL) with lights is extremely suitable for all level photographers from amateurs to professionals. It is a perfect solution for producing photo and video for web retailers and commercial product catalog. Very easy to use and setup in seconds. Moreover, this kit includes an extra 45 watts small light for better effect. With our professional photo umbrellas and lights kit, you can take your perfect photos with excellent photographic effect.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Other").id, name: "Westcott Illusions uLite Green Screen Photo Lighting Kit", photo_url: "https://lh4.googleusercontent.com/public/mXZVXqj8b9VDxPyjUqIv61DqdnX_02PTp3M87IrYZubXD0zzDmMv7b3FV5dLsLdZI131_o323X9fhzBNR7DuKZXBQVIrKC8ZluYN-hYdbYVTi-zvNv-6edWnfHeOtfa5bIqKv19gai6-yYk4OHSTzhE=s220-c", description: "Easy set up soft boxes are collapsible and set up and tear down in seconds Constant lights allow you to see lighting patterns instantly Can use with any point and shoot or digital SLR camera Educational DVD covers all aspects of set up - lighting and posing All-inclusive kit allows you to start shooting right away", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Other").id, name: "Shure SM58 - microphone", photo_url: "https://lh4.googleusercontent.com/public/mqPry6tk83Saq6QqfTmrM9vTvNzcXrWwWh1_Xf743aaPSrWwbDD10frdDYibHNmtKMjlLF_C17ojO_hZL_Aiiu8xPZYvFUiq2jA4Kka1-Na1vr-DfWS7E7ViGI1ynJM=s220-c", description: "The legendary Shure vocal mic is tuned to accentuate the warmth and clarity of lead and back-up vocals. It's consistently the first choice of performers around the globe. The Shure SM58 is a unidirectional (cardioid) dynamic vocal microphone designed for professional vocal use in live performance, sound reinforcement, and studio recording. A highly effective, built-in, spherical filter minimizes wind and breath 'pop' noise. A cardioid pickup pattern isolates the main sound source while minimizing unwanted background noise. The SM58 has a tailored vocal response for a sound, which is a world standard. Rugged construction, a proven shock mount system, and a steel mesh grille ensure that even with rough handling, the SM58 will perform consistently. Outdoors or indoors, singing, speech - the SM58 is the overwhelming choice of professionals.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Other").id, name: "RDE - VideoMic Pro On-Camera Microphone Rod VMP", photo_url: "https://lh4.googleusercontent.com/public/62vysFBztmVIkYbYNiTj02l-soRuRD3aTcjFTTJwfhBb4O0UkCn--AdBMbLsXH32HfAWZz12if1J59Y5PgUaBzu5KJv8QLF4REeMcTPvibxjSYWqe4tcmh2Iu3cqcGNM8-gTJEJ_6mwkMK60vqXFigMZzVOwHRx21mJuhoZNWxY7Q3xxdNs_eRe52wNACsvUSyLBUjv4r9U=s220-c", description: "A standard-size shoe mount and 3/8 thread allow widespread connectivity.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Other").id, name: "Apogee Mic Studio Quality Microphone for iPad, Iphone and Mac", photo_url: "https://lh6.googleusercontent.com/public/QLZkFlj5wpdxoxnxgqbZMkEIZJyT7fn9tZgPiikorkQ-6yEEgfniBl1Hjf-kbYpUZyGv1UHIzy1wvyZBCDRLT7GacKFShZO0vQXGsOKfrgnj58Y2sI6LX52676eh1qOTg8n8LfAsOQ8Dk21AvgS_mpFoog=s220-c", description: "PureDIGITAL connection for pristine sound quality. Studio quality cardioid condenser microphone. 44.1/48 kHz, 24-bit analog-to-digital conversion Studio quality microphone preamp with up to 40dB of gain. No configuration, just plug in and record-and Made in U.S.A.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 },
  { category_id: Category.find_by_name("Other").id, name: "Zoidberg", photo_url: "http://www.8daysageek.com/wp-content/uploads/2011/11/zoidberg.png", description: "This is NOT a piece of equipment.", daily_price: 10, weekly_price: 40, monthly_price: 100, user_id: 1 }
]

items.shuffle.each do |item|
  i = Item.new
  i.category_id = item[:category_id]
  i.user_id = item[:user_id]
  i.name = item[:name]
  i.photo_url = item[:photo_url]
  i.description = item[:description]
  i.daily_price = item[:daily_price]
  i.weekly_price = item[:weekly_price]
  i.monthly_price = item[:monthly_price]
  i.save
  puts i.errors.full_messages
end

puts "#{Category.count} Categories in your database!"
puts "#{Item.count} Items in your database!"
